### ISSUE TITLE
Can't resolve './SkillBar.scss' 

### ISSUE THREAD

**Issue by IamLizu** [crisboarna/react-skillbars#175]
`SkillBar.scss` from parent dir is required, but not present in installed module,
![image](https://user-images.githubusercontent.com/26184316/80584235-3081ce80-8a33-11ea-9d61-20d577539a5f.png)

Here is my code,
```
import React from "react"
import SkillBar from "react-skillbars"

const skills = [
    {type: "Java", level: 85},
    {type: "Javascript", level: 75},
  ];

export default function ind() {
    return(
        <SkillBar skills={skills}/>
    )
}
```

I am getting, 

> ./node_modules/react-skillbars/build-module/components/SkillBar.js
> Module not found: Can't resolve './SkillBar.scss' in 'F:\react\node_modules\react-skillbars\build-module\components'

![image](https://user-images.githubusercontent.com/26184316/80580344-37a5de00-8a2d-11ea-87b9-085ca63e03f5.png)

What am I missing?

**Comment by nafiul90** [comment]
[https://create-react-app.dev/docs/adding-a-sass-stylesheet/](url)

follow this instruction. you need to install scss loader.

npm install node-sass --save

**Comment by IamLizu** [comment]
Thanks a ton 👏

**Comment by IamLizu** [comment]
If I manually create the scss file in the react-skillbars folder, it compiles fine. I doubt if its about a missing sass loader.

**Comment by verma-ananya** [comment]
yes, facing the same issue and I  think it's not regarding just the sass loader (installed scss loader). Also, the provided link seems to be broken. 
@IamLizu , can you please elaborate on the creation of the scss file? As in, are the details provided on the site or you did all the additions your own?

**Comment by IamLizu** [comment]
@verma-ananya,  I did the manual file creation on my own, it was not instructed in the site, it won't be because maybe the file should be inside the package in the first place.   
If you browse the repo, you'll find the missing [SkillBar.scss](https://github.com/crisboarna/react-skillbars/blob/master/src/lib/components/SkillBar.scss) file. Now, go to your `node_modules` directory inside of your project dir. Navigate to `react-skillbars` > `build_module` > `components`, then create/paste that file in that directory.   
As you can see, SkillBar.scss has being looked in that directory, so placing it there manually will do.

**Comment by crisboarna** [comment]
Updated build process to include css. Please try with version 1.16.1.

**Comment by crisboarna** [comment]
@IamLizu @verma-ananya @nafiul90 
Updated build process to include css. Please try with version 1.16.1.

**Comment by IamLizu** [comment]
@crisboarna, yes, I can confirm, compilation issue is gone. I think this can be closed now.
