### ISSUE TITLE
Cannot deploy on Netlify using Gatsby.

### ISSUE THREAD

**Issue by yu-ming-chen** [crisboarna/react-skillbars#198]
Cannot deploy on Netlify using Gatsby.
<img width="1112" alt="Screenshot 2021-03-31 at 2 18 23 AM" src="https://user-images.githubusercontent.com/56465070/113036903-62f9f580-91c7-11eb-8c1f-ceb0250f7da5.png">
<img width="785" alt="Screenshot 2021-03-31 at 2 19 23 AM" src="https://user-images.githubusercontent.com/56465070/113037033-8b81ef80-91c7-11eb-9b27-a70a81d681b1.png">

**Comment by crisboarna** [comment]
Hi,

I have removed any reference to `document` and `window`. The `IntersectionObserver` being used now is guarded for server side so it should pass now.

Hopefully you will try it out in a future project of yours :)
